In [15]:
import pandas as pd
df = pd.read_csv(r"C:\Users\tania\Desktop\empdata.csv")
df
                 

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [16]:
df.shape

(53, 9)

In [17]:
df.isnull()

Emp ID  Last Name  First Name   Dept  E-mail  Phone Ext  Location  \
0    False      False       False  False   False      False     False   
1    False      False       False  False   False      False     False   
2    False      False       False  False   False      False     False   
3    False      False       False  False   False      False     False   
4    False      False       False  False   False      False     False   
5    False      False       False  False   False      False     False   
6    False      False       False  False   False      False     False   
7    False      False       False  False   False      False     False   
8    False      False       False  False   False      False     False   
9    False      False       False  False   False      False     False   
10   False      False       False  False   False      False     False   
11   False      False       False  False   False      False     False   
12   False      False       False  False   False      False     False   
13   False      False       False  False   False      False     False   
14   False      False       False  False   False      False     False   
15   False      False       False  False   False      False     False   
16   False      False       False  False   False      False     False   
17   False      False       False  False   False      False     False   
18   False      False       False  False   False      False     False   
19   False      False       False  False   False      False     False   
20   False      False       False  False   False      False     False   
21   False      False       False  False   False      False     False   
22   False      False       False  False   False      False     False   
23   False      False       False  False   False      False     False   
24   False      False       False  False   False      False     False   
25   False      False       False  False   False      False     False   
26   False      False       False  False   False      False     False   
27   False      False       False  False   False      False     False   
28   False      False       False  False   False      False     False   
29   False      False       False  False   False      False     False   
30   False      False       False  False   False      False     False   
31   False      False       False  False   False      False     False   
32   False      False       False  False   False      False     False   
33   False      False       False  False   False      False     False   
34   False      False       False  False   False      False     False   
35   False      False       False  False   False      False     False   
36   False      False       False  False   False      False     False   
37   False      False       False  False   False      False     False   
38   False      False       False  False   False      False     False   
39   False      False       False  False   False      False     False   
40   False      False       False  False   False      False     False   
41   False      False       False  False   False      False     False   
42   False      False       False  False   False      False     False   
43   False      False       False  False   False      False     False   
44   False      False       False  False   False      False     False   
45   False      False       False  False   False      False     False   
46   False      False       False  False   False      False     False   
47   False      False       False  False   False      False     False   
48   False      False       False  False   False      False     False   
49   False      False       False  False   False      False     False   
50   False      False       False  False   False      False     False   
51   False      False       False  False   False      False     False   
52   False      False       False  False   False      False     False   

    Hire Date    Age  
0       False  False  
1       False  

In [18]:
df.isnull().sum()

Emp ID        0
Last Name     0
First Name    0
Dept          0
E-mail        0
Phone Ext     0
Location      0
Hire Date     0
Age           9
dtype: int64

In [19]:
df.isnull().sum().sum()

9

In [20]:
#Dropping the rows with null values

df2 = df.dropna()
df2

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
51    1426    Lampstone       Pete   SA      petel        128  Building 3   
52    1949      Sampson      Carla   SA     carlas        147  Building 3   

    Hire Date   Age  
0   04-Mar-89  30.0  
1   06-Aug-90  35.0  
2   05-Jul-98  50.0  
4   28-Sep-89  40.0  
6   06-Mar-85  34.0  
7   04-Jan-85  45.0  
8   03-Apr-97  34.0  
9   18-Apr-91  54.0  
10  25-Mar-92  55.0  
12  14-Feb-98  46.0  
13  03-Jan-85  32.0  
14  13-Apr-82  33.0  
15  28-Jun-97  48.0  
16  17-Nov-91  55.0  
18  16-Apr-90  57.0  
19  13-Nov-86  44.0  
20  01-Mar-96  32.0  
21  25-Oct-79  29.0  
22  01-Apr-86  28.0  
24  07-Aug-92  57.0  
25  19-Jun-85  40.0  
26  28-Jan-87  39.0  
27  14-Dec-87  29.0  
28  08-Sep

In [21]:
df

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [22]:
# filling Null value with median of the column age
df3 = df.fillna(value=df['Age'].median())
df3

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [23]:
df3.isnull().sum()

Emp ID        0
Last Name     0
First Name    0
Dept          0
E-mail        0
Phone Ext     0
Location      0
Hire Date     0
Age           0
dtype: int64

In [24]:
#Filling Null value with max value

df4 = df.fillna(value=df['Age'].max())
df4

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [25]:
df4.isnull().sum().sum()

0

In [26]:
#Filling Null value with pad value

df5 = df.fillna(method = 'pad')
df5

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [27]:
#Filling Null value with next value

df6 = df.fillna(method = 'bfill')
df6

Emp ID    Last Name First Name Dept     E-mail  Phone Ext    Location  \
0     1814     Al-Sabah      Daoud   HR     daouda        103  Building 3   
1     1721      Alstain     Isolde   HR    isoldea        102  Building 3   
2     1999      Atherly  Katherine   HR     kathya        428  Building 3   
3     1196     Atherton      Katie   HR     katiea        289  Building 3   
4     1906      Bankler     Rowena   SA    rowenab        155  Building 3   
5     1792       Barton     Eileen   AT    eileenb        111  Building 1   
6     1516         Bell        Tom   AC       tomb        105  Building 2   
7     1284     Bellwood      Frank   MK     frankb        124  Building 1   
8     1982      Berwick     Elaine   SA   eberwick        202  Building 3   
9     1167      Berwick        Sam   SA       samb        119  Building 3   
10    1673     Boughton      Frank   AD  fboughton        112  Building 2   
11    1758       Brwyne      Melia   AC     meliab        107  Building 2   
12    1990        Chang    Jessica   MF      jessc        198  Building 1   
13    1290       Cooper      Linda   AD     lindac        113  Building 2   
14    1966    Cortlandt    Charles   SA   charlesc        159  Building 3   
15    1983      Corwick       Judy   AT      judyc        154  Building 1   
16    1964      Corwick        Rob   AC    robertc        108  Building 2   
17    1293     Cronwith      Brent   HR     brentc        205  Building 3   
18    1672  Dixon-Waite    Sherrie   MF   sherried        114  Building 1   
19    1960     Fontaine       Jean   MF      jeanf        150  Building 1   
20    1975     Franklin      Larry   AC     larryf        125  Building 2   
21    1056     Gonzales        Joe   AT       joeg        121  Building 1   
22    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   
23    1152      Henders       Mark   AD      markh        118  Building 2   
24    1075         Kane     Sheryl   AD    sherylk        126  Building 2   
25    1509       Kegler        Pam   AT       pamk        135  Building 1   
26    1529    Kellerman     Tommie   MK       tomk        129  Building 1   
27    1656      Kourios       Theo   MF      theok        149  Building 1   
28    1426    Lampstone       Pete   SA      petel        128  Building 3   
29    1984    MacDonald    Bronwyn   SA      bronm        204  Building 3   
30    1676       Miller      Janet   MK     janetm        115  Building 1   
31    1995      Mivelli      Maria   AT     mariam        198  Building 1   
32    1359       Morton     Norman   SA    normanm        153  Building 3   
33    1931      Mueller     Ursula   AC    ursulam        110  Building 2   
34    1723      Sammler       Mark   MK      marks        145  Building 1   
35    1949      Sampson      Carla   SA     carlas        147  Building 3   
36    1067        Scote       Gail   AT      gails        123  Building 1   
37    1299      Simpson    Sandrae   MF   sandraes        127  Building 1   
38    1302      Sindole      Randy   MK     randys        139  Building 1   
39    1922        Smith    Barbara   SA   barbaras        146  Building 3   
40    1310        Smith      Ellen   MF     ellens        137  Building 1   
41    9999        Smith      Hazel   SA     hazelg        109  Building 3   
42    1054        Smith     Howard   AT    howards        148  Building 1   
43    1333     Szcznyck     Tadeuz   HR    tadeuzs        122  Building 3   
44    1572      Tuppman  Lise-Anne   SA  lise-annt        116  Building 3   
45    1329       Vuanuo      Tuome   AC     tuomev        151  Building 2   
46    1368           Wu      Tammy   AD     tammyw        132  Building 2   
47    1352       Ygarre       Lisa   SA      lisay        100  Building 3   
48    1908       Zostoc    Melissa   AT   melissaz        152  Building 1   
49    1290       Cooper      Linda   AD     lindac        113  Building 2   
50    1078     Hapsbuch   Kendrick   AC  kendrickh        101  Building 2   


In [29]:
#Filling Null value with imputer function

import numpy as np
from sklearn.impute import SimpleImputer

In [43]:
s_impute=SimpleImputer(missing_values="NaN",strategy="mean",verbose=0)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Emp ID      53 non-null     int64  
 1   Last Name   53 non-null     object 
 2   First Name  53 non-null     object 
 3   Dept        53 non-null     object 
 4   E-mail      53 non-null     object 
 5   Phone Ext   53 non-null     int64  
 6   Location    53 non-null     object 
 7   Hire Date   53 non-null     object 
 8   Age         44 non-null     float64
dtypes: float64(1), int64(2), object(6)
memory usage: 3.9+ KB


In [54]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
employees_imp=pd.DataFrame(imputer.fit_transform(df['Age'].values.reshape(-1,1)))
employees_imp.isna().sum().sort_values(ascending = False)

0    0
dtype: int64

In [55]:
df.head(5)

Emp ID Last Name First Name Dept   E-mail  Phone Ext    Location  \
0    1814  Al-Sabah      Daoud   HR   daouda        103  Building 3   
1    1721   Alstain     Isolde   HR  isoldea        102  Building 3   
2    1999   Atherly  Katherine   HR   kathya        428  Building 3   
3    1196  Atherton      Katie   HR   katiea        289  Building 3   
4    1906   Bankler     Rowena   SA  rowenab        155  Building 3   

   Hire Date   Age  
0  04-Mar-89  30.0  
1  06-Aug-90  35.0  
2  05-Jul-98  50.0  
3  01-Apr-98   NaN  
4  28-Sep-89  40.0

In [56]:
employees_imp.head()

0
0  30.00
1  35.00
2  50.00
3  41.75
4  40.00

In [58]:
#performing one hot encoding 
print(df['Dept'].unique())


['HR' 'SA' 'AT' 'AC' 'MK' 'AD' 'MF']


In [59]:
print(df['Location'].unique())

['Building 3' 'Building 1' 'Building 2']


In [60]:

df['Location'].value_counts()


Building 3    20
Building 1    19
Building 2    14
Name: Location, dtype: int64

In [61]:
df['Dept'].value_counts()

SA    14
AC     8
AT     8
AD     6
MF     6
HR     6
MK     5
Name: Dept, dtype: int64

In [64]:
one_hot_encoded_data = pd.get_dummies(df3, columns = ['Dept', 'Location'])
print(one_hot_encoded_data)


    Emp ID    Last Name First Name     E-mail  Phone Ext  Hire Date   Age  \
0     1814     Al-Sabah      Daoud     daouda        103  04-Mar-89  30.0   
1     1721      Alstain     Isolde    isoldea        102  06-Aug-90  35.0   
2     1999      Atherly  Katherine     kathya        428  05-Jul-98  50.0   
3     1196     Atherton      Katie     katiea        289  01-Apr-98  40.0   
4     1906      Bankler     Rowena    rowenab        155  28-Sep-89  40.0   
5     1792       Barton     Eileen    eileenb        111  24-Dec-90  40.0   
6     1516         Bell        Tom       tomb        105  06-Mar-85  34.0   
7     1284     Bellwood      Frank     frankb        124  04-Jan-85  45.0   
8     1982      Berwick     Elaine   eberwick        202  03-Apr-97  34.0   
9     1167      Berwick        Sam       samb        119  18-Apr-91  54.0   
10    1673     Boughton      Frank  fboughton        112  25-Mar-92  55.0   
11    1758       Brwyne      Melia     meliab        107  18-Mar-82  40.0   

In [65]:
#performing label encoding on data

from sklearn import preprocessing


label_encoder = preprocessing.LabelEncoder()

df['Location']= label_encoder.fit_transform(df['Location'])

df['Location'].unique()



array([2, 0, 1])

In [66]:
#Performing standardization

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

In [67]:
dataset = load_iris()
object= StandardScaler()
  
i_data = dataset.data
response = dataset.target
  
scale = object.fit_transform(i_data) 
print(scale)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [68]:
#Performing normalization

from sklearn import preprocessing


In [69]:
x_array = np.array([2,1,9,6,7,3,8,7,6])
normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)

[[0.11026357 0.05513178 0.49618606 0.33079071 0.38592249 0.16539535
  0.44105428 0.38592249 0.33079071]]
